Dependency management
virtualidentityag/conditional-resource-loader pull request #9
Opened 2017-01-04 13:38 UTC by alxbenz

Changes to resourceLoader to use promises to resolve dependencies.

Please have a look and comment or improve upon the code.

2017-01-04 13:51 UTC, lhwparis requested changes

2017-01-04 13:51 UTC, lhwparis commented on bower.json
> +  "version": "0.1.0",
there is a missmatch with the versions we have tagged in github. we are already on 1.0.1 there.

2017-01-04 13:51 UTC, lhwparis commented on demo/demo.html
> +<!--
indentation seems to be broken. mix of tabs and spaces. can you place our default .editorconfig in this repo and reformat?

2017-01-04 13:53 UTC, lhwparis commented on resourceLoader.js
> +          $.each(resource.paths, function() {
indentation seems to be broken (tabs and spaces) can you put our default editorconfig in this repo and reformat?

2017-01-11 11:46 UTC, smohadjer commented on resourceLoader.js
> +function absolutePath(urlString) {
The logic for absolute path handling doesn't seem robust enough to me. If I run the demo page from http://localhost/conditional-resource-loader/demo/demo.html or from http://localhost:8080/demo/demo.html, in both cases all resources fail to load due to wrongly normalized paths.

2017-01-11 12:16 UTC, alxbenz commented on resourceLoader.js
> +function absolutePath(urlString) {
I adjusted the path handling to consider the port. So http://localhost:8080/demo/demo.html should be working now. I couldn't reproduce your behaviour for http://localhost/conditional-resource-loader/demo/demo.html.
Do you have any idea to get the path handling more robust?

2017-01-13 09:23 UTC, janrembold commented
Looks fine to me.

2017-01-19 15:52 UTC, timomayer approved these changes

2017-01-19 15:52 UTC, timomayer commented on demo/demo-debug.html
> +			Resources are loaded in order of dependencies: component1.js -> component2.js -> demo4.css
@smohadjer as discussed in the ticket js/jquery.component1.js will never be loaded so the dependecies wont either.

2017-01-26 08:39 UTC, merged